[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "${https://eth-sepolia.g.alchemy.com/v2/flbH2g7X16RKad8MLf-tozjM5LGxnx65}", sepolia-arb = "${https://arb-sepolia.g.alchemy.com/v2/flbH2g7X16RKad8MLf-tozjM5LGxnx65}"}
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink=lib/chainlink/contracts/src/v0.8/",
    "@chainlink-local/=lib/chainlink-local/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
